### ISSUE TITLE
When phone has orientation unlocked, if phone is oriented, UI elements redraw without refresh

### ISSUE THREAD

**Issue by Maelstromeous** [xplodwild/android_packages_apps_Focal#17]
When the app is rendering a panorama or a photosphere picture, if the phone has orientation settings turned on, the UI loading bars and toasts redraw, with no refresh, resulting in a Windows XP style of infinite redraw.

**Comment by Maelstromeous** [comment]
Ahh this is the same as issue #8. Feel free to close :-)

**Comment by xplodwild** [comment]
:)
