### ISSUE TITLE
set pic size   crash

### ISSUE THREAD

**Issue by ivan19871002** [xplodwild/android_packages_apps_Focal#22]
E/AndroidRuntime( 1952): FATAL EXCEPTION: main
E/AndroidRuntime( 1952): java.lang.RuntimeException: setParameters failed
E/AndroidRuntime( 1952):    at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime( 1952):    at android.hardware.Camera.setParameters(Camera.java:1540)
E/AndroidRuntime( 1952):    at org.cyanogenmod.focal.CameraManager.setPictureSize(CameraManager.java:542)
E/AndroidRuntime( 1952):    at org.cyanogenmod.focal.widgets.SettingsWidget$5$2.onClick(SettingsWidget.java:182)
E/AndroidRuntime( 1952):    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
E/AndroidRuntime( 1952):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1952):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1952):    at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 1952):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1952):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 1952):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 1952):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1952):    at dalvik.system.NativeStart.main(Native Method)

**Comment by ivan19871002** [comment]
devices: xiaomi 2/2s/2a  
ROM: AOSP 4.3

**Comment by RyanDawkins** [comment]
http://stackoverflow.com/questions/3890381/camera-setparameters-failed-in-android
I found this.. looking for the surface changed method.

Edit: Found it, Perhaps in this method is where the problem happens?
https://github.com/xplodwild/android_packages_apps_Focal/blob/master/src/org/cyanogenmod/focal/CameraManager.java#L1256

**Comment by xplodwild** [comment]
setParameters failed can happen for various reasons - at one point, it can fail just because you're doing two calls too fast. A better way to debug this would be to check the logcat for Camera HAL debugging messages, where we could maybe have a message such as "Invalid parameter xxx for yyy", which would indicate the exact cause of the failure.

**Comment by RyanDawkins** [comment]
I don't have a the xiaomi device, but I would love to fix this problem. @ivan19871002 could you get a logcat of this?
