### ISSUE TITLE
Live preview has different cropping than final shot

### ISSUE THREAD

**Issue by CerebroJD** [xplodwild/android_packages_apps_Focal#24]
When taking a picture, the preview onscreen has about 30% cropped from the right, top, and bottom. When the image is captured, there is WAY more content shown.

Framing (You can see that the letters only extend from Y to P):
![img_20130925_115457](https://f.cloud.github.com/assets/723614/1211599/14f9f68e-260c-11e3-9abb-8737a1d4dbef.JPG)

Actual (Letters extend from Y to the  ] key):
![img_20130925_115326394](https://f.cloud.github.com/assets/723614/1211602/1f6cf724-260c-11e3-9e10-39eb2ece376c.jpg)

(Disregard wierd rotation on second pic, looks fine on my phone, but my computer and this browser seem to thing its rotated 90 degrees left. Possible bug? Different than the last 90 degree one?)

**Comment by xplodwild** [comment]
This is linked to #2 - feel free to add more details to that ticket if you want :)
I'm tagging this one as duplicate, because internally it's the same issue. Many people also requested a way to have a non-cropped view (a centered-inside one instead), that I can add in the future.
