### ISSUE TITLE
Include Focal in F-Droid (currently on hold due to prebuilt libraries)

### ISSUE THREAD

**Issue by mvglasow** [xplodwild/android_packages_apps_Focal#55]
Focal was submitted for inclusion in F-Droid a while back. The submission is currently on hold due to the numerous libraries in `assets`.

F-Droid builds all apps from source to make sure that the published source will actually compile, and that the binaries they distribute correspond to the published source code. Therefore they would need the source code for these libraries (at least a pointer where to find it).

The discussion on the F-Droid forum is at:
https://f-droid.org/forums/topic/focal-camera-app/

**Comment by xplodwild** [comment]
https://github.com/xplodwild/android_external_Focal
