### ISSUE TITLE
Improve swipe to delete UX in quick gallery

### ISSUE THREAD

**Issue by dpashkevich** [xplodwild/android_packages_apps_Focal#6]
I found it very difficult to delete pictures via swiping. When doing a typical fast swipe, the picture only "jerks" to the direction of swipe but "gets stuck" on its way and comes back in place. I have to swipe really slowly and carefully for it to go all the way up/down and get deleted.

**Comment by dpashkevich** [comment]
I just tried the latest version (1.0-dfa5ee8) and the swipe seems to work OK now, thanks!

**Comment by xplodwild** [comment]
Great :) Closing
