### ISSUE TITLE
version for arm-7

### ISSUE THREAD

**Issue by k3b** [xplodwild/android_packages_apps_Focal#71]
According to https://f-droid.org/repository/browse/?fdfilter=photo&fdid=fr.xplod.focal this app needs armeabi-v7a. unfortunately my android 4.4 handset has only "ARM Cortex-A7" so the app cannot be installed via fdroid-app-store. is it possible to recompile the native libs for a7?

**Comment by xplodwild** [comment]
Native libs are used for PhotoSphere. If your device doesn't support NEON instructions (A7 isn't an architecture, it should still be armeabi-v7, but probably doesn't support NEON), it is too old to support PhotoSphere anyway.
